"""One-shot generator for the 17-chain example mapping.

Run: `uv run python scripts/gen_example_mapping.py > config/mapping.example.yaml`
"""
from __future__ import annotations

# layer: (fmap_count, rows, cols, fmaps_per_chain)
PARTITION = {
    "L1": (1, 28, 28, 1),
    "L2": (4, 24, 24, 1),
    "L3": (4, 12, 12, 1),
    "L4": (12, 8, 8, 3),     # 4 chains x 3 fmaps
    "L5": (12, 4, 4, 4),     # 3 chains x 4 fmaps
    "L6": (1, 1, 10, 1),
}
SLAB_SPACING_MM = 30.0
PITCH_MM = 10.0
GPIO_PINS = [4, 5, 6, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]  # 17 GPIOs


def main() -> None:
    print("# Generated by scripts/gen_example_mapping.py -- edit by hand for tuning.")
    print("layers:")
    chains_so_far = 0
    z = 0.0
    chains_declared: list[tuple[int, int]] = []  # (chain_id, length)
    for layer, (fcount, rows, cols, per_chain) in PARTITION.items():
        print(f"  {layer}:")
        print("    feature_maps:")
        layer_chains_used: dict[int, int] = {}  # chain_id -> pixel count
        for fm_id in range(fcount):
            chain_for_this_fm = chains_so_far + fm_id // per_chain
            offset = (fm_id % per_chain) * rows * cols
            print(f"      - id: {fm_id}")
            print(f"        chain_id: {chain_for_this_fm}")
            print(f"        offset_in_chain: {offset}")
            print(f"        rows: {rows}")
            print(f"        cols: {cols}")
            print(f"        origin_mm: [{fm_id * (cols + 2) * PITCH_MM}, 0, {z}]")
            print(f"        pitch_mm: [{PITCH_MM}, {PITCH_MM}]")
            print(f"        order: row_major_snake")
            layer_chains_used[chain_for_this_fm] = layer_chains_used.get(chain_for_this_fm, 0) + rows * cols
        for cid, length in sorted(layer_chains_used.items()):
            chains_declared.append((cid, length))
        n_chains = -(-fcount // per_chain)
        chains_so_far += n_chains
        z += SLAB_SPACING_MM
    print("chains:")
    for cid, length in chains_declared:
        gpio = GPIO_PINS[cid]
        print(f"  - id: {cid}")
        print(f"    gpio: {gpio}")
        print(f"    length: {length}")


if __name__ == "__main__":
    main()
