"""One-shot generator for the 17-chain example mapping.

Each feature map gets its OWN plane in 3D space. Within a layer, fmaps stack
along Z with INTRA_LAYER_SPACING_MM between adjacent fmaps. Between layers,
INTER_LAYER_SPACING_MM separates the last fmap of one layer from the first
fmap of the next. All fmaps are centered on the X/Y origin so the stack
reads as a deck of cards from any viewing angle.

Run: `uv run python scripts/gen_example_mapping.py > config/mapping.example.yaml`
"""
from __future__ import annotations

# layer: (fmap_count, rows, cols, fmaps_per_chain)
PARTITION = {
    "L1": (1, 28, 28, 1),
    "L2": (4, 24, 24, 1),
    "L3": (4, 12, 12, 1),
    "L4": (12, 8, 8, 3),     # 4 chains x 3 fmaps
    "L5": (12, 4, 4, 4),     # 3 chains x 4 fmaps
    "L6": (1, 1, 10, 1),
}
PITCH_MM = 10.0
INTRA_LAYER_SPACING_MM = 40.0  # between adjacent fmaps inside one layer
INTER_LAYER_SPACING_MM = 80.0  # between last fmap of layer N and first of N+1
GPIO_PINS = [4, 5, 6, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]


def main() -> None:
    print("# Generated by scripts/gen_example_mapping.py -- each feature map on its own plane.")
    print("layers:")
    chains_so_far = 0
    z_cursor = 0.0
    chains_declared: list[tuple[int, int]] = []  # (chain_id, length)
    for layer, (fcount, rows, cols, per_chain) in PARTITION.items():
        print(f"  {layer}:")
        print("    feature_maps:")
        # Center each fmap on (0, 0) in XY so the stack of fmaps lines up.
        x0 = -(cols - 1) * PITCH_MM / 2.0
        y0 = -(rows - 1) * PITCH_MM / 2.0
        layer_chains_used: dict[int, int] = {}
        for fm_id in range(fcount):
            chain_for_this_fm = chains_so_far + fm_id // per_chain
            offset = (fm_id % per_chain) * rows * cols
            z = z_cursor + fm_id * INTRA_LAYER_SPACING_MM
            print(f"      - id: {fm_id}")
            print(f"        chain_id: {chain_for_this_fm}")
            print(f"        offset_in_chain: {offset}")
            print(f"        rows: {rows}")
            print(f"        cols: {cols}")
            print(f"        origin_mm: [{x0}, {y0}, {z}]")
            print(f"        pitch_mm: [{PITCH_MM}, {PITCH_MM}]")
            print(f"        order: column_major_snake")
            layer_chains_used[chain_for_this_fm] = layer_chains_used.get(chain_for_this_fm, 0) + rows * cols
        for cid, length in sorted(layer_chains_used.items()):
            chains_declared.append((cid, length))
        n_chains = -(-fcount // per_chain)
        chains_so_far += n_chains
        # Move past this layer's full Z extent, then add the inter-layer gap.
        z_cursor += (fcount - 1) * INTRA_LAYER_SPACING_MM + INTER_LAYER_SPACING_MM
    print("chains:")
    for cid, length in chains_declared:
        gpio = GPIO_PINS[cid]
        print(f"  - id: {cid}")
        print(f"    gpio: {gpio}")
        print(f"    length: {length}")


if __name__ == "__main__":
    main()
